
apiVersion: batch/v1
kind: Job
metadata:
  name: hyperpitrix-generate-kubeconfig
  namespace: openpitrix-system
  labels:
    app: hyperpitrix
    job: hyperpitrix-generate-kubeconfig
    version: v0.0.1
spec:
  backoffLimit: 100
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: hyperpitrix
        job: hyperpitrix-generate-kubeconfig
        version: v0.0.1
      name: hyperpitrix-generate-kubeconfig-job
    spec:
      initContainers:
        - name: wait-runtime-manager
          image: busybox:1.28.4
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z hyperpitrix.openpitrix-system.svc 9103; do echo "waiting for runtime-manager"; sleep 2; done;']
      containers:
        - command: ["generate-kubeconfig","-srv","https://kubernetes.default"]
          name: hyperpitrix-generate-kubeconfig
          imagePullPolicy: IfNotPresent
          image: openpitrix/generate-kubeconfig:latest
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30